repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.0.191'
  hooks:
    - id: ruff
      # Respect `exclude` and `extend-exclude` settings.
      # args: ["--extend-exclude"]
      args: [--fix,--exit-zero]


# - repo: https://github.com/astral-sh/ruff-pre-commit
#   # Ruff version.
#   rev: v0.1.2
#   hooks:
#     - id: ruff
#       args: [--fix, --exit-non-zero-on-fix]
